#9
c=float(input("Enter the celsius degree:"))
f=c*9/5+32
print(f,'\n',sep='')
#10
def sgn(number):
    return int(number)+1
cake=int(input("Please enter the number of cakes:"))
sugar=sgn(cake/48*1.5)
butter=sgn(cake/48)
powder=sgn(cake/48*2.75)
print("Need:",sugar," cup of sugar,",butter," cup of butter,",powder," cup of powder.\n",sep='')
#11
m=int(input("Male student:"))
w=int(input("Female student:"))
r=float(m)/float(w)
print("Male students/Female students is",format(r,'.2%'))
#12
Buyin=2000
Pay=40.00
TotalP=float(Buyin*Pay)
Commision_a=float(TotalP*0.03)
Soldout=2000
Income=42.75
TotalI=float(Soldout*Income)
Commision_b=float(TotalI*0.03)
Profit=TotalI-TotalP-Commision_a-Commision_b
if Profit>0:
    print("Joe had a positive income.\n")
else:
    print("Joe had a loss.")
#13
Row=float(input("Please enter the length of earth row in inch:"))
Width=float(input("Please enter the width between two puncheon:"))
Distance=float(input("Please enter the distance of two adjacent grapes:"))
Vine=int((Row-2*Width)/Distance)
print("The best planting number is",Vine)
#14
Principal=float(input("Please enter the initial principal:"))
Rate=float(input("Please enter the interest rate:"))
NT=int(input("Please enter the times of counting compound interest per year:"))
TY=int(input("Plese enter the years of deposit:"))
A=Principal*(1+Rate/NT)**(NT*TY)
print("After",TY,"years,the total amount of funds in the account is",format(A,'.2f'))
#15
import turtle
turtle.pensize(5)
turtle.pencolor('red')
turtle.left(45)
turtle.forward(100)
for num in range(1,4):
  turtle.right(90)
  turtle.forward(100)
turtle.forward(100)
for num in range(1,4):
  turtle.left(90)
  turtle.forward(100)
turtle.clearscreen()
turtle.pensize(5)
turtle.pencolor('yellow')
turtle.penup()
turtle.goto(-50,0)
turtle.pendown()
turtle.left(30)
turtle.forward(57.73)
turtle.right(60)
turtle.forward(57.73)
turtle.right(150)
turtle.forward(100)
turtle.right(120)
turtle.forward(100)
turtle.right(120)
turtle.forward(100)
turtle.goto(0,0)
turtle.clearscreen()
turtle.pensize(5)
turtle.pencolor('green')
turtle.right(45)
turtle.forward(141.4213562)
turtle.left(135)
turtle.forward(100)
for num in range(1,4):
  turtle.left(90)
  turtle.forward(100)
turtle.penup()
turtle.goto(0,0)
turtle.pendown()
turtle.setheading(135)
turtle.forward(141.4213562)
turtle.left(135)
turtle.forward(100)
for num in range(1,4):
  turtle.left(90)
  turtle.forward(100)
turtle.penup()
turtle.goto(0,100)
turtle.pendown()
turtle.goto(100,0)
turtle.penup()
turtle.goto(0,-100)
turtle.pendown()
turtle.goto(-100,0)
turtle.clearscreen()
turtle.pensize(5)
turtle.pencolor('blue')
turtle.circle(100)
turtle.penup()
turtle.goto(-200,0)
turtle.pendown()
turtle.pencolor('red')
turtle.circle(100)
turtle.penup()
turtle.goto(200,0)
turtle.pendown()
turtle.pencolor('green')
turtle.circle(100)
turtle.penup()
turtle.goto(-100,-100)
turtle.pendown()
turtle.pencolor('black')
turtle.circle(100)
turtle.penup()
turtle.goto(100,-100)
turtle.pendown()
turtle.pencolor('yellow')
turtle.circle(100)
turtle.clearscreen()
turtle.pensize(5)
turtle.pencolor('black')
turtle.speed(1)
turtle.forward(20)
turtle.left(90)
turtle.circle(20)
turtle.right(90)
turtle.penup()
turtle.goto(0,0)
turtle.pendown()
turtle.goto(200,0)
turtle.setheading(135)
turtle.forward(10)
turtle.penup()
turtle.goto(200,0)
turtle.setheading(225)
turtle.pendown()
turtle.forward(10)
turtle.penup()
turtle.goto(200,0)
turtle.pendown()
turtle.write('East')
turtle.penup()
turtle.goto(0,0)
turtle.pendown()
turtle.goto(0,200)
turtle.setheading(225)
turtle.forward(10)
turtle.penup()
turtle.goto(0,200)
turtle.setheading(-45)
turtle.pendown()
turtle.forward(10)
turtle.penup()
turtle.goto(0,200)
turtle.pendown()
turtle.write('North')
turtle.penup()
turtle.goto(0,0)
turtle.pendown()
turtle.goto(0,-200)
turtle.setheading(135)
turtle.forward(10)
turtle.penup()
turtle.goto(0,-200)
turtle.setheading(45)
turtle.pendown()
turtle.forward(10)
turtle.penup()
turtle.goto(0,-200)
turtle.pendown()
turtle.write('South')
turtle.penup()
turtle.goto(0,0)
turtle.pendown()
turtle.goto(-200,0)
turtle.setheading(45)
turtle.forward(10)
turtle.penup()
turtle.goto(-200,0)
turtle.setheading(-45)
turtle.pendown()
turtle.forward(10)
turtle.penup()
turtle.goto(-200,0)
turtle.pendown()
turtle.write('West')
turtle.clearscreen()
turtle.pencolor('purple')
turtle.pensize(5)
turtle.goto(100,-100)
turtle.goto(-100,100)
turtle.goto(-100,-100)
turtle.goto(100,100)
turtle.goto(100,-100)
turtle.goto(64,-100)
turtle.penup()
turtle.goto(42,-100)
turtle.pendown()
turtle.goto(5,-100)
turtle.penup()
turtle.goto(-5,-100)
turtle.pendown()
turtle.goto(-42,-100)
turtle.penup()
turtle.goto(-64,-100)
turtle.pendown()
turtle.goto(-100,-100)
turtle.penup()
turtle.goto(100,100)
turtle.pendown()
turtle.goto(64,100)
turtle.penup()
turtle.goto(42,100)
turtle.pendown()
turtle.goto(5,100)
turtle.penup()
turtle.goto(-5,100)
turtle.pendown()
turtle.goto(-42,100)
turtle.penup()
turtle.goto(-64,100)
turtle.pendown()
turtle.goto(-100,100)
turtle.done()
